language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0

before_script:
  - git submodule update --remote --recursive

script: 
  - bundle exec rake spec:ci
  - bundle install
  - rake gem
  - gem install ./authorizenet-1.8.6.gem
  - cd sample-code-ruby
  - for i in `ls */*.rb`;do ruby $i;done
  
